Repository meta-pytorch/tritonbench, pull requests merged in 2025-09, with the labels that each got.

#360 adding dynamic benchmark loader
  tritonbench/utils/constants.py
  tritonbench/utils/parser.py
  tritonbench/utils/triton_op.py
Labels: cla signed, fb-exported

#333 Add inductor_benchmarker as latency measurement option
  tritonbench/components/do_bench/run.py
  tritonbench/utils/parser.py
  tritonbench/utils/triton_op.py
Labels: cla signed

#383 [run_config] Add test shapes for blackwell_attentions
  benchmarks/run_config/bf16_blackwell_attentions_fwd_shape1.yaml
  benchmarks/run_config/bf16_blackwell_attentions_fwd_shape2.yaml
  benchmarks/run_config/bf16_blackwell_attentions_fwd_shape3.yaml
Labels: cla signed

#386 Add `--latency-measure-mode=profiler` support
  tritonbench/components/do_bench/run.py
  tritonbench/utils/parser.py
  tritonbench/utils/triton_op.py
Labels: cla signed

#387 [python_utils] add try import utils
  tritonbench/operators/flash_attention/operator.py
  tritonbench/utils/python_utils.py
Labels: cla signed

#395 Add eager and torch.compile implementations for gdpa
  tritonbench/operators/gdpa/operator.py
Labels: cla signed

#399 int4_gemm: improve PyTorch eager impl to match Triton impl behavior
  tritonbench/operators/int4_gemm/int4_gemm.py
Labels: cla signed

#403 Link to fbsource
  CONTRIBUTING.md
Labels: cla signed, fb-exported

#401 Profiler mode: Add ProfilerActivity.CPU to tracked activities
  tritonbench/components/do_bench/run.py
Labels: cla signed

#404 Revert D81714673
  CONTRIBUTING.md
Labels: cla signed, fb-exported

#407 Fix sum kernel's accuracy check method
  tritonbench/operators/sum/operator.py
Labels: cla signed

#397 FAv4 CuteDSL Bench for decode
  tritonbench/operators/decoding_attention/operator.py
Labels: cla signed, fb-exported

#418 Fix geglu accuracy check
  tritonbench/operators/geglu/operator.py
Labels: cla signed

#419 [GDPA] TLX bwd kernel
  tritonbench/operators/gdpa/gdpa.py
  tritonbench/operators/gdpa/gdpa_blackwell_tlx.py
  tritonbench/operators/gdpa/operator.py
Labels: cla signed

#428 Verify experimental_descriptor in Triton version
  tritonbench/operators/fp8_gemm/fp8_gemm.py
  tritonbench/utils/triton_utils.py
Labels: cla signed, fb-exported, meta-exported

#431 grouped_gemm: move preparation step into measured function for fair timing comparison
  tritonbench/operators/grouped_gemm/operator.py
Labels: cla signed

#426 Add ability to read shapes from json
  tritonbench/operators/grouped_gemm/operator.py
Labels: cla signed, fb-exported, meta-exported

#430 Improve FWD/BWD accuracy checks for rms norm
  tritonbench/operators/rms_norm/operator.py
Labels: cla signed, fb-exported, meta-exported

#437 Fix lint
  tritonbench/operators/rms_norm/operator.py
Labels: cla signed

#438 [Grouped Gemm] Add versions of benchmarks without input preprocessing
  tritonbench/operators/grouped_gemm/operator.py
Labels: cla signed, fb-exported, meta-exported

#434 [Grouped Gemm] Add ability to autotune CuteDSL kernel
  tritonbench/operators/grouped_gemm/cutedsl/autotuner.py
  tritonbench/operators/grouped_gemm/cutedsl/kernels.py
  tritonbench/operators/grouped_gemm/operator.py
Labels: cla signed, fb-exported, meta-exported

#424 Support per-row scaling
  tritonbench/operators/fp8_gemm/fp8_gemm.py
  tritonbench/operators/fp8_gemm/persistent.py
Labels: cla signed, fb-exported, meta-exported

#442 decoding_attention: gate fbcode import
  tritonbench/operators/decoding_attention/operator.py
Labels: cla signed

#425 Add epilogue subtiling to persistent + TMA kernel
  tritonbench/operators/fp8_gemm/persistent.py
Labels: cla signed, fb-exported, meta-exported

#449 [run_utils] Apply run options to config
  benchmarks/dump_ir/run.py
  run.py
  tritonbench/operators/layer_norm/operator.py
  tritonbench/utils/run_utils.py
Labels: cla signed

#415 adding swa to tritonbench
  tritonbench/operators/blackwell_attentions/operator.py
Labels: cla signed, fb-exported, meta-exported

#452 [Fix] gather_gemv small fix
  tritonbench/operators/gather_gemv/operator.py
  tritonbench/operators/gather_gemv/triton_gather_gemv.py
Labels: cla signed

#454 [ab test] fix triton repo location
  tritonbench/utils/scuba_utils.py
Labels: cla signed

#459 Profiler mode: fix missing CUDA events
  tritonbench/components/do_bench/run.py
Labels: cla signed

#460 Add `--exit-on-exception` to exit process on any exception
  tritonbench/utils/parser.py
  tritonbench/utils/triton_op.py
Labels: cla signed

#461 [backends] add mojo matmul
  benchmarks/mojo_matmul/run.py
Labels: cla signed

#420 [power] Add initial power chart support
  .github/workflows/_linux-test-h100.yml
  requirements.txt
  test/test_gpu/skip_tests_h100_pytorch.yaml
  test/test_gpu/skip_tests_h100_triton_main.yaml
  tritonbench/components/power/__init__.py
  tritonbench/components/power/chart.py
  tritonbench/operators/softmax/operator.py
  tritonbench/utils/parser.py
  tritonbench/utils/triton_op.py
Labels: cla signed

#447 Extend triton_mm auto-tune options for HIM shapes
  tritonbench/operators/fp8_gemm_rowwise/aoti_fp8_triton_mm.py
Labels: cla signed, fb-exported, meta-exported

#466 rms_norm: pass weight as input args, to reuse the same weight for all impls
  tritonbench/operators/rms_norm/operator.py
Labels: cla signed

#467 Fix BWD gradient check; improved BWD check for rms_norm and layer_norm
  tritonbench/operators/layer_norm/operator.py
  tritonbench/operators/rms_norm/operator.py
  tritonbench/utils/triton_op.py
Labels: cla signed

#451 Add mpp_analysis benchmark
  benchmarks/mpp_analysis/run.py
  tritonbench/operators/gdpa/gdpa_blackwell_tlx.py
Labels: cla signed, fb-exported, meta-exported

#473 Contribute fp8_gemm Blackwell-specific per-row scaling config
  benchmarks/run_config/fp8_gemm_blackwell_rowwise_config_1.yaml
Labels: cla signed, fb-exported, meta-exported

#470 Fix more linting
  benchmarks/mojo_matmul/run.py
  run.py
Labels: cla signed, fb-exported, meta-exported

#478 Make sure all default-stream produced input tensors have finished writing before starting cudagraph
  tritonbench/utils/triton_op.py
Labels: cla signed

#477 cross_entropy: modify Liger triton kernel to be cudagraph compatible
  tritonbench/operators/cross_entropy/liger_cross_entropy.py
  tritonbench/operators/cross_entropy/operator.py
Labels: cla signed

#357 Improve TritonParse Log Organization and Force Overwrite
  tritonbench/utils/tritonparse_utils.py
Labels: cla signed

#481 jagged_softmax: Add `torch_compile_jagged_softmax_torch_sum` for more performant torch.compile impl
  tritonbench/operators/jagged_softmax/operator.py
Labels: cla signed

#482 softmax: change baseline to directly use F.softmax
  tritonbench/operators/softmax/operator.py
Labels: cla signed

#483 Fix cudagraph support for rms_norm bwd and layer_norm bwd
  tritonbench/operators/layer_norm/operator.py
  tritonbench/operators/rms_norm/operator.py
Labels: cla signed

#486 rms_norm: use in_place=False for Liger kernel
  tritonbench/operators/rms_norm/operator.py
Labels: cla signed

#485 Skip benchmarks that are not enabled in --only mode
  tritonbench/utils/parser.py
  tritonbench/utils/triton_op.py
Labels: cla signed, fb-exported, meta-exported

#448 Optimized Triton LayerNorm Backwards
  tritonbench/operators/layer_norm/fused_triton.py
  tritonbench/operators/layer_norm/operator.py
Labels: cla signed, fb-exported, meta-exported

#472 jagged_sum accuracy small fix
  tritonbench/operators/jagged_sum/operator.py
  tritonbench/utils/jagged_utils.py
Labels: cla signed

#488 Add persistent FA for blackwell
  tritonbench/kernels/blackwell_triton_fused_attention.py
  tritonbench/operators/blackwell_attentions/operator.py
Labels: cla signed

#487 add non-persistent variant with data partitioning
  tritonbench/kernels/blackwell_triton_fused_attention_dp.py
  tritonbench/operators/blackwell_attentions/operator.py
Labels: cla signed

#497 [Grouped Gemm][CuTeDSL] Force unrolling of certain loops
  tritonbench/operators/grouped_gemm/cutedsl/kernels.py
Labels: cla signed, fb-exported, meta-exported

#499 [amd] Update rocm to 7.0
  tools/rocm_utils.py
Labels: cla signed, module: rocm, ciflow/rocm
