Repository meta-pytorch/tritonbench, pull requests merged in 2025-08, with the labels that each got.

#324 Adding Stream-K persistent matmul kernel (#309)
  tritonbench/operators/gemm/operator.py
  tritonbench/operators/gemm/stream_k.py
Labels: cla signed, fb-exported

#327 [easy] Remove unnecessary comment
  run.py
Labels: cla signed

#331 Update repo owner
  .ci/test_infra/oss_ci_benchmark_v3.py
  .github/workflows/_linux-benchmark-abtest-h100.yml
  .github/workflows/_linux-benchmark-h100.yml
  .github/workflows/_linux-test-h100.yml
  .github/workflows/docker-rocm.yaml
  .github/workflows/docker.yaml
  README.md
  docker/infra/values.yaml
  docker/tritonbench-nightly.dockerfile
  docker/tritonbench-rocm-nightly.dockerfile
  docs/metrics.md
  install.py
  tritonbench/utils/triton_op.py
  tritonbench/utils/tritonparse_utils.py
Labels: cla signed, module: rocm

#337 Fix cuda_time metric
  tritonbench/components/do_bench/cuda_time.py
Labels: cla signed

#336 Add input loader module for fp8_gemm
  tritonbench/operators/fp8_gemm/fp8_gemm.py
Labels: cla signed, fb-exported

#340 Add Support for TLX matmul
  tritonbench/operators/gemm/operator.py
  tritonbench/operators/gemm/stream_k.py
  tritonbench/operators/gemm/tlx_matmul.py
  tritonbench/utils/triton_utils.py
Labels: cla signed, fb-exported

#343 [infra] Fix docker workflow
  .github/workflows/docker-rocm.yaml
  .github/workflows/docker.yaml
  docker/infra/README.md
  docker/infra/values.yaml
  run.py
  tools/python_utils.py
  tritonbench/operators/addmm/operator.py
  tritonbench/operators/fp8_gemm/fp8_gemm.py
  tritonbench/utils/triton_utils.py
Labels: cla signed, module: rocm

#347 [rope][inductor] Always reset dynamo
  tritonbench/utils/triton_op.py
Labels: cla signed

#339 Add amax as default per-tensor scaling factor for fp8_gemm benchmark
  tritonbench/operators/fp8_gemm/fp8_gemm.py
Labels: cla signed, fb-exported

#358 Use non-opt as baseline
  tritonbench/operators/gdpa/operator.py
Labels: cla signed, fb-exported

#356 Make the result consistent with FAv4 benchmark
  tritonbench/operators/blackwell_attentions/generate_inputs.py
  tritonbench/operators/blackwell_attentions/operator.py
Labels: cla signed, fb-exported

#318 [GDPA] add tlx fwd for blackwell
  tritonbench/operators/gdpa/gdpa_blackwell_tlx.py
  tritonbench/operators/gdpa/operator.py
Labels: cla signed

#364 [gdpa] subtiling activation to reduce register pressure
  tritonbench/operators/gdpa/gdpa_blackwell_tlx.py
Labels: cla signed

#362 [run_config][gemm] Enable exhaustive search for gemm
  benchmarks/run_config/gemm_config_1_exhaustive.yaml
  benchmarks/run_config/gemm_config_1_maxautotune.yaml
  tritonbench/operators/gemm/operator.py
  tritonbench/utils/run_utils.py
Labels: cla signed

#373 Fix flex_attention test
  test/test_gpu/main.py
  tritonbench/operators/flex_attention/operator.py
  tritonbench/utils/triton_op.py
Labels: cla signed, fb-exported

#375 [FA][Blackwell] Add triton version with autoWS
  tritonbench/kernels/blackwell_triton_fused_attention.py
  tritonbench/operators/blackwell_attentions/operator.py
Labels: cla signed

#377 [FA] Fix tutorial blackwell perf
  tritonbench/kernels/blackwell_triton_fused_attention.py
Labels: cla signed
